#!/usr/bin/env fish
#MISE description="Creates a new github release, and pushes to Hex.pm"
#MISE depends="tag"

set -l current_version (string match -gr 'version: "(.*?)"' -- (cat mix.exs))

gh release create v$current_version --generate-notes

mix hex.publish
